<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::table('class_schedules', function (Blueprint $table) {
            // Check if index exists before adding to avoid duplication errors 
            // (though standard specific names are generated by Laravel, safer to just add if we want to ensure)
            // MySQL FKs usually create an index, but separate index for searching is fine.
            $table->index('schedule_date');
            $table->index('status');
            $table->index('tutor_id');
            $table->index('class_id');
            $table->index('subject_id');
        });

        Schema::table('attendance', function (Blueprint $table) {
            $table->index('attendance_date');
            $table->index('status');
            $table->index('student_id');
            $table->index('class_id');
        });

        Schema::table('notifications', function (Blueprint $table) {
            $table->index('created_at');
            $table->index('status');
            $table->index('type');
            $table->index('user_id');
            $table->index('student_id');
        });

        Schema::table('fees', function (Blueprint $table) {
            $table->index('status');
            $table->index('due_date');
            $table->index('student_id');
        });

        Schema::table('students', function (Blueprint $table) {
            $table->index('user_id');
            $table->index('class_id');
            $table->index('enrollment_date');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('class_schedules', function (Blueprint $table) {
            $table->dropIndex(['schedule_date']);
            $table->dropIndex(['status']);
            $table->dropIndex(['tutor_id']);
            $table->dropIndex(['class_id']);
            $table->dropIndex(['subject_id']);
        });

        Schema::table('attendance', function (Blueprint $table) {
            $table->dropIndex(['attendance_date']);
            $table->dropIndex(['status']);
            $table->dropIndex(['student_id']);
            $table->dropIndex(['class_id']);
        });

        Schema::table('notifications', function (Blueprint $table) {
            $table->dropIndex(['created_at']);
            $table->dropIndex(['status']);
            $table->dropIndex(['type']);
            $table->dropIndex(['user_id']);
            $table->dropIndex(['student_id']);
        });

        Schema::table('fees', function (Blueprint $table) {
            $table->dropIndex(['status']);
            $table->dropIndex(['due_date']);
            $table->dropIndex(['student_id']);
        });

        Schema::table('students', function (Blueprint $table) {
            $table->dropIndex(['user_id']);
            $table->dropIndex(['class_id']);
            $table->dropIndex(['enrollment_date']);
        });
    }
};
